### ISSUE TITLE
CSV transform

### ISSUE THREAD

**Issue by ghost** [ahdis/fhir-mapping-tutorial#23]
Hello, I followed this tutorial to try a transformation from csv to fhir. I got the mapping of the csv done and after executing "POST {{host}}/r4/StructureMap/$transform?source=http://hl7.org/fhir/StructureMap/csv-transform", with my csv file as the body, I got the following error as operation outcome:

HTTP/1.1 500 Server Error
Date: Mon, 01 Mar 2021 09:31:25 GMT
X-Powered-By: HAPI FHIR 5.3.0-SNAPSHOT/1a2403400b/2021-02-15 REST Server (FHIR Server; FHIR 4.0.1/R4)
X-Request-ID: 1BWrd2QshcTkMt45
Content-Type: application/fhir+xml;charset=utf-8
Transfer-Encoding: chunked
Via: 1.1 google
Alt-Svc: clear
Connection: close

<OperationOutcome 
  xmlns="http://hl7.org/fhir">
  <issue>
    <severity value="error"></severity>
    <code value="processing"></code>
    <diagnostics value="Failed to call access method: org.hl7.fhir.exceptions.FHIRFormatError: Content is not allowed in prolog. at line 0 col 0"></diagnostics>
  </issue>
</OperationOutcome>

Could you please offer any guide on how to resolve this?
I have attached my csv file, mapping file, result of structure map:
[csvmap.pdf](https://github.com/ahdis/fhir-mapping-tutorial/files/6060655/csvmap.pdf)
[csvtransform.txt](https://github.com/ahdis/fhir-mapping-tutorial/files/6060656/csvtransform.txt)
[structuremap result.pdf](https://github.com/ahdis/fhir-mapping-tutorial/files/6060657/structuremap.result.pdf)

Thank you

**Comment by oliveregger** [comment]
which server are you using? hapi-fhir server has not the capability to parse directly csv files, if you provide a PR for it, I'm happy to test it out. see also discussion on https://chat.fhir.org/#narrow/stream/179166-implementers/topic/StructureMap.20for.20FHIR.20to.2Ffrom.20CSV

**Comment by ghost** [comment]
> which server are you using? hapi-fhir server has not the capability to parse directly csv files, if you provide a PR for it, I'm happy to test it out. see also discussion on https://chat.fhir.org/#narrow/stream/179166-implementers/topic/StructureMap.20for.20FHIR.20to.2Ffrom.20CSV

Thank you so much for your response. I used hapi fhir server. I will try it using using vonk server and see the outcome. I appreciate the link you sent too. It is helpful.
