### ISSUE TITLE
missing aliases in fhir tutorial

### ISSUE THREAD

**Issue by oliveregger** [ahdis/fhir-mapping-tutorial#27]
I try the next step and transform the source (except steps 1,2,10) then I get an error. The reason is missing aliases. If I add aliases
"http://hl7.org/fhir/StructureDefinition/tutorial-left" as source -> uses "http://hl7.org/fhir/StructureDefinition/tutorial-left" alias TLeft as source
and the same with TRight in all steps then all transformations start working.

**Comment by oliveregger** [comment]
The second thing - please add ".project" to gitignore.

**Comment by igorboss** [comment]
Still actual
